[2025-09-01T06:26:02.359+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.load manual__2025-09-01T06:25:55.182725+00:00 [queued]>
[2025-09-01T06:26:02.373+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.load manual__2025-09-01T06:25:55.182725+00:00 [queued]>
[2025-09-01T06:26:02.374+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-01T06:26:02.405+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load> on 2025-09-01 06:25:55.182725+00:00
[2025-09-01T06:26:02.437+0000] {standard_task_runner.py:60} INFO - Started process 900 to run task
[2025-09-01T06:26:02.465+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'load', 'manual__2025-09-01T06:25:55.182725+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpzamc5usx']
[2025-09-01T06:26:02.472+0000] {standard_task_runner.py:88} INFO - Job 26: Subtask load
[2025-09-01T06:26:02.564+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-01T06:26:02.779+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline.load manual__2025-09-01T06:25:55.182725+00:00 [running]> on host 857434650c3d
[2025-09-01T06:26:03.368+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T06:25:55.182725+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-01T06:25:55.182725+00:00'
[2025-09-01T06:26:03.377+0000] {logging_mixin.py:188} INFO - Running task: LOAD
[2025-09-01T06:26:03.378+0000] {logging_mixin.py:188} INFO - Simulating the loading of transformed data to a warehouse...
[2025-09-01T06:26:03.379+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-09-01T06:26:03.410+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=load, execution_date=20250901T062555, start_date=20250901T062602, end_date=20250901T062603
[2025-09-01T06:26:03.491+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-01T06:26:03.558+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
