[2025-08-29T03:24:02.539+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.load manual__2025-08-29T03:23:52.141287+00:00 [queued]>
[2025-08-29T03:24:02.558+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.load manual__2025-08-29T03:23:52.141287+00:00 [queued]>
[2025-08-29T03:24:02.558+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-08-29T03:24:02.585+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load> on 2025-08-29 03:23:52.141287+00:00
[2025-08-29T03:24:02.608+0000] {standard_task_runner.py:60} INFO - Started process 1285 to run task
[2025-08-29T03:24:02.625+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'load', 'manual__2025-08-29T03:23:52.141287+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpcz1rwml9']
[2025-08-29T03:24:02.628+0000] {standard_task_runner.py:88} INFO - Job 32: Subtask load
[2025-08-29T03:24:02.685+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-29T03:24:02.758+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline.load manual__2025-08-29T03:23:52.141287+00:00 [running]> on host 45d0ac61cfd5
[2025-08-29T03:24:03.006+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-08-29T03:23:52.141287+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-29T03:23:52.141287+00:00'
[2025-08-29T03:24:03.014+0000] {logging_mixin.py:188} INFO - Loading (fake)...
[2025-08-29T03:24:05.048+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-08-29T03:24:05.166+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=load, execution_date=20250829T032352, start_date=20250829T032402, end_date=20250829T032405
[2025-08-29T03:24:05.235+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-29T03:24:05.344+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
