[2025-09-02T03:21:45.587+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.archive manual__2025-09-02T03:19:14.717901+00:00 [queued]>
[2025-09-02T03:21:45.718+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.archive manual__2025-09-02T03:19:14.717901+00:00 [queued]>
[2025-09-02T03:21:45.729+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-02T03:21:45.825+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): archive> on 2025-09-02 03:19:14.717901+00:00
[2025-09-02T03:21:45.856+0000] {standard_task_runner.py:60} INFO - Started process 243 to run task
[2025-09-02T03:21:45.889+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'archive', 'manual__2025-09-02T03:19:14.717901+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp4sini24c']
[2025-09-02T03:21:45.909+0000] {standard_task_runner.py:88} INFO - Job 21: Subtask archive
[2025-09-02T03:21:46.037+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-02T03:21:46.455+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline.archive manual__2025-09-02T03:19:14.717901+00:00 [running]> on host f8a9cd7e9422
[2025-09-02T03:21:47.847+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='archive' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T03:19:14.717901+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-02T03:19:14.717901+00:00'
[2025-09-02T03:21:50.207+0000] {etl_pipeline.py:208} INFO - Archived 2025/09/02/8c327732-a4cc-4472-8744-008fa43dc692_applicants.csv from landing -> archive
[2025-09-02T03:21:50.235+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-09-02T03:21:50.439+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=archive, execution_date=20250902T031914, start_date=20250902T032145, end_date=20250902T032150
[2025-09-02T03:21:50.637+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-02T03:21:50.843+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
