[2025-08-28T08:27:26.532+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.load manual__2025-08-28T08:27:02.896782+00:00 [queued]>
[2025-08-28T08:27:26.584+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.load manual__2025-08-28T08:27:02.896782+00:00 [queued]>
[2025-08-28T08:27:26.585+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-08-28T08:27:26.644+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load> on 2025-08-28 08:27:02.896782+00:00
[2025-08-28T08:27:26.731+0000] {standard_task_runner.py:60} INFO - Started process 618 to run task
[2025-08-28T08:27:26.801+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'load', 'manual__2025-08-28T08:27:02.896782+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpf5zfe1qu']
[2025-08-28T08:27:26.856+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask load
[2025-08-28T08:27:27.231+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-28T08:27:28.828+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline.load manual__2025-08-28T08:27:02.896782+00:00 [running]> on host dd18df0f367e
[2025-08-28T08:27:31.356+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-08-28T08:27:02.896782+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-28T08:27:02.896782+00:00'
[2025-08-28T08:27:31.521+0000] {logging_mixin.py:188} INFO - Loading (fake)...
[2025-08-28T08:27:33.543+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-08-28T08:27:34.384+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=load, execution_date=20250828T082702, start_date=20250828T082726, end_date=20250828T082734
[2025-08-28T08:27:34.727+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-28T08:27:35.063+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
