[2025-09-02T07:07:46.246+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.archive manual__2025-09-02T07:07:08.610445+00:00 [queued]>
[2025-09-02T07:07:46.271+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.archive manual__2025-09-02T07:07:08.610445+00:00 [queued]>
[2025-09-02T07:07:46.272+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-02T07:07:46.303+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): archive> on 2025-09-02 07:07:08.610445+00:00
[2025-09-02T07:07:46.335+0000] {standard_task_runner.py:60} INFO - Started process 197 to run task
[2025-09-02T07:07:46.345+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'archive', 'manual__2025-09-02T07:07:08.610445+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpbjexqwjg']
[2025-09-02T07:07:46.354+0000] {standard_task_runner.py:88} INFO - Job 29: Subtask archive
[2025-09-02T07:07:46.422+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-02T07:07:46.537+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline.archive manual__2025-09-02T07:07:08.610445+00:00 [running]> on host f1d436f67367
[2025-09-02T07:07:46.705+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='archive' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T07:07:08.610445+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-02T07:07:08.610445+00:00'
[2025-09-02T07:07:47.782+0000] {etl_pipeline.py:208} INFO - Archived 2025/09/02/16f1bb10-be2c-40d0-a140-83c5785c6158_applicants.csv from uploads -> archive
[2025-09-02T07:07:47.787+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-09-02T07:07:47.875+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=archive, execution_date=20250902T070708, start_date=20250902T070746, end_date=20250902T070747
[2025-09-02T07:07:48.038+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-02T07:07:48.174+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
