[2025-09-01T09:10:57.608+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.archive manual__2025-09-01T09:10:40.350863+00:00 [queued]>
[2025-09-01T09:10:57.617+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.archive manual__2025-09-01T09:10:40.350863+00:00 [queued]>
[2025-09-01T09:10:57.618+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-01T09:10:57.628+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): archive> on 2025-09-01 09:10:40.350863+00:00
[2025-09-01T09:10:57.639+0000] {standard_task_runner.py:60} INFO - Started process 627 to run task
[2025-09-01T09:10:57.643+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'archive', 'manual__2025-09-01T09:10:40.350863+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp495xhuop']
[2025-09-01T09:10:57.645+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask archive
[2025-09-01T09:10:57.664+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-01T09:10:57.697+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline.archive manual__2025-09-01T09:10:40.350863+00:00 [running]> on host f8a9cd7e9422
[2025-09-01T09:10:57.757+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='archive' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T09:10:40.350863+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-01T09:10:40.350863+00:00'
[2025-09-01T09:10:57.935+0000] {etl_pipeline.py:208} INFO - Archived 2025/09/01/1889dd28-9118-4f0a-ac83-2b48def2ba12_applicants.csv from landing -> archive
[2025-09-01T09:10:57.936+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-09-01T09:10:57.956+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=archive, execution_date=20250901T091040, start_date=20250901T091057, end_date=20250901T091057
[2025-09-01T09:10:57.987+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-01T09:10:58.028+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
