[2025-08-28T09:18:56.000+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.load manual__2025-08-28T09:18:42.627571+00:00 [queued]>
[2025-08-28T09:18:56.017+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.load manual__2025-08-28T09:18:42.627571+00:00 [queued]>
[2025-08-28T09:18:56.018+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-08-28T09:18:56.034+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load> on 2025-08-28 09:18:42.627571+00:00
[2025-08-28T09:18:56.056+0000] {standard_task_runner.py:60} INFO - Started process 265 to run task
[2025-08-28T09:18:56.066+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'load', 'manual__2025-08-28T09:18:42.627571+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpvyzm0rp2']
[2025-08-28T09:18:56.082+0000] {standard_task_runner.py:88} INFO - Job 23: Subtask load
[2025-08-28T09:18:56.135+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-28T09:18:56.298+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline.load manual__2025-08-28T09:18:42.627571+00:00 [running]> on host 45d0ac61cfd5
[2025-08-28T09:18:56.503+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-08-28T09:18:42.627571+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-28T09:18:42.627571+00:00'
[2025-08-28T09:18:56.505+0000] {logging_mixin.py:188} INFO - Loading (fake)...
[2025-08-28T09:18:58.511+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-08-28T09:18:58.644+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=load, execution_date=20250828T091842, start_date=20250828T091856, end_date=20250828T091858
[2025-08-28T09:18:58.703+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-28T09:18:58.793+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
